server:
    addr: ":8080"
    admin_api_key: "changeme-admin-key"


db:
  driver: "pgx"   # or "sqlite3"
  dsn: "postgres://postgres:postgres@localhost:5432/raalisence?sslmode=disable"
  path: "./raalisence.db"   # if using sqlite3


signing:
  private_key_pem: |
    -----BEGIN EC PRIVATE KEY-----
    # paste generated dev key here
    -----END EC PRIVATE KEY-----
    public_key_pem: |
    -----BEGIN PUBLIC KEY-----
    # matching public key here
    -----END PUBLIC KEY-----