server:
  addr: ":8080"
  # bcrypt hashes of admin API tokens. Generate with:
  #   python scripts/gen.py <token>
  admin_api_key_hashes:
    - "$2a$10$exampleplaceholderhashforadmin"

db:
  driver: "sqlite3"   # or "postgresql"
  dsn: "postgresql://postgres:postgres@localhost:5432/raalisence"
  path: "./raalisence.db"   # if using sqlite3

signing:
  private_key_pem: |
    -----BEGIN EC PRIVATE KEY-----
    # paste generated dev key here
    -----END EC PRIVATE KEY-----
  public_key_pem: |
    -----BEGIN PUBLIC KEY-----
    # matching public key here
    -----END PUBLIC KEY-----