version: '3.8'

services:
  raalisence-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PYTHONPATH=/app
      - RA_DB_PATH=/app/data/raalisence.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL database for production use
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: raalisence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
