apiVersion: v1
kind: ConfigMap
metadata:
  name: raalisence-sqlite-migrations
  labels:
    app: raalisence
data:
  0001_init.sql: |
    CREATE TABLE IF NOT EXISTS licenses (
        id TEXT PRIMARY KEY,
        license_key TEXT UNIQUE NOT NULL,
        customer TEXT NOT NULL,
        machine_id TEXT NOT NULL,
        features TEXT NOT NULL DEFAULT '{}',
        expires_at TEXT NOT NULL,
        revoked INTEGER NOT NULL DEFAULT 0,
        last_seen_at TEXT NULL,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE INDEX IF NOT EXISTS idx_licenses_license_key ON licenses(license_key);

    CREATE TRIGGER IF NOT EXISTS trg_licenses_updated_at
    AFTER UPDATE ON licenses
    FOR EACH ROW
    BEGIN
      UPDATE licenses SET updated_at = datetime('now') WHERE id = OLD.id;
    END;