apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raalisence-sqlite-pvc
  labels:
    app: raalisence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo # adjust to your GKE default if different